services:
  react_front_end:
    build: client\
    container_name: react_front_end
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    environment:
        - CHOKIDAR_USEPOLLING=true
